/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.conectar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class formulario extends javax.swing.JFrame {
conectar conecto;

    PreparedStatement  ps;
    ResultSet rs;


private static Connection conn; 
    private static final String driver="com.mysql.jdbc.Driver";
    private static final String user="root"; 
    private static final String pass="";
    private static final String url="jdbc:mysql://localhost:3306/licoreria";

    public formulario() {
        initComponents();
    
    
}
    //este metodo nos retorna la conexion
    public Connection getConnection (){
        
        
        Connection conn= null;
        try {
            Class.forName(driver);
            conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(url, user, pass);
            if (conn != null){
                System.out.println("La conexion se establecio bien con el DB");
            }
        } catch (ClassNotFoundException | SQLException e) {
         System.out.println("Error al conectar con la DB"+ e);
    }
        return conn;
        
    }
    //metodo para desconectar
    public void desconectar (){
        conn= null;
        if (conn== null) {
             System.out.println("Se desconecto del DB");
            
        }
    } 

    public void borrarcaja(){ 
            
       cajacedula.setText(null);
       cajanombre.setText(null);
       cajatelefono.setText(null);
       cajadireccion.setText(null);
       cajaemail.setText(null);
       caja2000.setText(null);
       caja1000.setText(null);
       caja750.setText(null);
       caja700.setText(null);
       caja375.setText(null);
       caja250.setText(null);     
       caja170.setText(null);      
    }


















    /**
     * Creates new form formulario
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cajacedula = new javax.swing.JTextField();
        cajanombre = new javax.swing.JTextField();
        cajatelefono = new javax.swing.JTextField();
        cajadireccion = new javax.swing.JTextField();
        cajaemail = new javax.swing.JTextField();
        caja2000 = new javax.swing.JTextField();
        caja1000 = new javax.swing.JTextField();
        caja750 = new javax.swing.JTextField();
        caja700 = new javax.swing.JTextField();
        caja375 = new javax.swing.JTextField();
        caja250 = new javax.swing.JTextField();
        caja170 = new javax.swing.JTextField();
        bconectar = new javax.swing.JButton();
        benviar = new javax.swing.JButton();
        bdesconectar = new javax.swing.JButton();
        jlfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Compra de aguardiente Nectar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 380, 30));

        jLabel2.setText("cedula");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 50, -1));

        jLabel3.setText("nombre y apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel4.setText("telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel5.setText("direccion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel6.setText("email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel7.setText("Nectar 2000");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel8.setText("Nectar 1000");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel9.setText("Nectar 750");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jLabel10.setText("Nectar 700");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        jLabel12.setText("Nectar 375");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        jLabel13.setText("Nectar 170");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        jLabel14.setText("Nectar 250");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("digite enfrente de cada producto la cantidad que decea");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));
        getContentPane().add(cajacedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 240, -1));
        getContentPane().add(cajanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 240, -1));

        cajatelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajatelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(cajatelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 240, -1));

        cajadireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajadireccionActionPerformed(evt);
            }
        });
        getContentPane().add(cajadireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 240, 30));
        getContentPane().add(cajaemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 240, -1));

        caja2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja2000ActionPerformed(evt);
            }
        });
        getContentPane().add(caja2000, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 60, -1));

        caja1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja1000ActionPerformed(evt);
            }
        });
        getContentPane().add(caja1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 60, -1));
        getContentPane().add(caja750, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 60, -1));
        getContentPane().add(caja700, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 60, -1));

        caja375.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja375ActionPerformed(evt);
            }
        });
        getContentPane().add(caja375, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 60, -1));
        getContentPane().add(caja250, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 60, -1));

        caja170.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja170ActionPerformed(evt);
            }
        });
        getContentPane().add(caja170, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 60, -1));

        bconectar.setText("conectar");
        bconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconectarActionPerformed(evt);
            }
        });
        getContentPane().add(bconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, -1, -1));

        benviar.setText("enviar pedido");
        benviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benviarActionPerformed(evt);
            }
        });
        getContentPane().add(benviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, -1, -1));

        bdesconectar.setText("desconectar");
        bdesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(bdesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 670, -1, -1));

        jlfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FONDO.png"))); // NOI18N
        jlfondo.setText("jLabel1");
        getContentPane().add(jlfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 800, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajatelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajatelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajatelefonoActionPerformed

    private void cajadireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajadireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajadireccionActionPerformed

    private void caja170ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja170ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja170ActionPerformed

    private void caja1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja1000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja1000ActionPerformed

    private void caja375ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja375ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja375ActionPerformed

    private void caja2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja2000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja2000ActionPerformed

    private void bconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconectarActionPerformed
        conecto = new conectar ();
        Connection reg = conecto.getConnection ();
    }//GEN-LAST:event_bconectarActionPerformed

    private void benviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benviarActionPerformed
        Connection conn = null;
        conn = getConnection();
        try {
            
           PreparedStatement ps = conn.prepareStatement("INSTERT INTO `datos` (`cedula`, `nombres`, `telefono`, `direccion`, `email`, `nectar2000`, `nectar1000`, `nectar750`, `nectar700`, `nectar375`, `nectar250`, `nectar170`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, cajacedula.getText());
            ps.setString(2, cajanombre.getText());
            ps.setString(3, cajatelefono.getText());
            ps.setString(4, cajadireccion.getText());
            ps.setString(5, cajaemail.getText());
            ps.setString(6, caja2000.getText());
            ps.setString(7, caja1000.getText());
            ps.setString(8, caja750.getText());
            ps.setString(9, caja700.getText());
            ps.setString(10, caja375.getText());
            ps.setString(11, caja250.getText());
            ps.setString(12, caja170.getText());
            
            int result = ps.executeUpdate();
            
            if (result > 0) {
                    JOptionPane.showMessageDialog(null,"el envio fue procesado");
                    borrarcaja ();
                } else {
                    JOptionPane.showMessageDialog(null,"el envio no fue procesado");
                }
            
            conn.close();
            
            
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_benviarActionPerformed

    private void bdesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdesconectarActionPerformed
        conecto.desconectar();
    }//GEN-LAST:event_bdesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bconectar;
    private javax.swing.JButton bdesconectar;
    private javax.swing.JButton benviar;
    private javax.swing.JTextField caja1000;
    private javax.swing.JTextField caja170;
    private javax.swing.JTextField caja2000;
    private javax.swing.JTextField caja250;
    private javax.swing.JTextField caja375;
    private javax.swing.JTextField caja700;
    private javax.swing.JTextField caja750;
    private javax.swing.JTextField cajacedula;
    private javax.swing.JTextField cajadireccion;
    private javax.swing.JTextField cajaemail;
    private javax.swing.JTextField cajanombre;
    private javax.swing.JTextField cajatelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlfondo;
    // End of variables declaration//GEN-END:variables
}
